name: AWS Connection Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  aws-connection:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2
      

    # Set up AWS CLI
    # - name: Set up AWS CLI
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1  # You can change this to your preferred region

    
    
    #   uses: aws-actions/configure-aws-credentials@v1
        with:
           role-to-assume: arn:aws:iam::237712307052:role/github-acations-openid
           role-session-name: githubactions
           aws-region: us-east-1  # You can change this to your preferred region


    
    # Check AWS connection using the `sts get-caller-identity` command
    - name: Check AWS Connection
      run: |
        echo "Checking AWS Connection..."
        aws sts get-caller-identity

    # List EC2 Instances
    - name: List EC2 Instances
      run: |
        echo "Listing EC2 Instances..."
        aws ec2 describe-instances --query "Reservations[].Instances[].InstanceId"
